# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.8

exclude: ^src/auditwheel/_vendor/

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: ^cache/
  - id: forbid-new-submodules
  - id: trailing-whitespace

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: ["--py38-plus"]

- repo: https://github.com/psf/black
  rev: 23.10.0
  hooks:
  - id: black

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["-a", "from __future__ import annotations"]
    exclude: ^tests/integration/.*/src/.*pyx$

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.6.1
  hooks:
  - id: mypy
    exclude: ^tests/integration/.*/.*$
    additional_dependencies:
      - types-requests
